### ISSUE TITLE
Compatible sensors for purchase

### ISSUE THREAD

**Issue by evilknivel** [mightymos/door-reed-rf#1]
Hi,. 

can you please provide a typ, name or nee link the device?

**Comment by mightymos** [comment]
Hi the aliexpress link provided in the readme is working for me. You can also search for "door sensor 433 mhz" and compare photos on aliexpress to the housing in the "photos" folder for this repository.

Were you able to find a similar looking sensor?

**Comment by evilknivel** [comment]
Maybe it is some kind of geoblock. I have found one wich looks like the pics but is much more expansive.

**Comment by mightymos** [comment]
You might have to change quantity to one. What's your link?

**Comment by evilknivel** [comment]
https://m.de.aliexpress.com/item/32690822120.html?spm=a2g0n.productlist.0.0.a1cbZmnEZmnErf&browser_id=efdbe72efdbe4235a6951fed01289329&aff_trace_key=63c670d36a8d4a1595680a53323c660a-1671780243695-06753-UneMJZVf&aff_platform=msite&m_page_id=6oxyg4zc6wkcas2g1859313c7b8114562d1b1c041e&gclid=&pdp_npi=2%40dis%21EUR%2122.48%2120.23%21%21%21%21%21%40211b88f016732098253646084e4a4b%2160526010673%21sea&curPageLogUid=A1E6o5znhJCL&algo_pvid=b5dcfdc6-fe83-4c6a-9407-411123a7e26b


This one

**Comment by mightymos** [comment]
Yeah that link switches to .us domain for me and shows me $17.10 / 2 pieces.
My link is 1 piece ($4.09 USD), 3 piece ($12.06), 6 piece ($23.81).

Try looking for "Water Leak Alarm Store" as the seller. I think this might be the link for store page:
https://www.aliexpress.com/store/1101889834?spm=a2g0o.detail.1000007.1.4ee610f3es4deG

**Comment by mightymos** [comment]
I also have a single spare sensor I could ship if needed.

**Comment by evilknivel** [comment]
Nope sadly for me the Shop have No listed Item. Thanks for you support i will Go in searching and come Back to this issue with a link.

**Comment by fastriker** [comment]
Someone [posted this link](https://community.home-assistant.io/t/budget-priced-wife-friendly-wireless-wall-switch-using-433mhz-and-mqtt/88281) under [the hackaday article](https://hackaday.com/2023/01/08/low-cost-433-mhz-door-sensors-get-open-firmware/). There the sensor is called GS-WDS07. 

But if I search for it on aliexpress I only get [one rather expensive result](https://www.aliexpress.com/item/32743291414.html). A search on google give quite some results but mostly the sensors are not available anymore. My guess: They are not produced anymore :(

**Comment by zindy** [comment]
@evilknivel Does this link work any better? https://www.aliexpress.com/item/1005003523731992.html

It's the same as sent by @mightymos but with no extra parameters in the URL.

Right now, shipping to Belgium is free and one item is 4 euro 89 (as of pre- hackaday article).

**Comment by fastriker** [comment]
I am not  @evilknivel but I can not open the link "Sorry, this item's currently unavailable in your location.". I am in Germany and I guess @evilknivel as well, because he posted a German aliexpress link. I also changed shipping to Belgium - still the same. Maybe a VPN works? Unfortunately I have no VPN in another country available right now.

**Comment by zindy** [comment]
@fastriker Sorry mate, VPN won't help: If I change the shipping country from Belgium to Germany, I get a "Page Not Found", so it looks like the seller won't deliver to Germany for some reason.

**Comment by evilknivel** [comment]
@fastriker yes i am from germany, too. So Looks like we german are unlucky today.

**Comment by fastriker** [comment]
@evilknivel scheint so :( 
@zindy thank you for testing it out! I can save the effort now for getting a VPN.

**Comment by mightymos** [comment]
@evilknivel @fastriker @zindy
When you all search in your regions what 433 MHz products do appear with reasonable prices, if any?
I'm considering ordering a few varieties to see if they use identical chips.
Even if the housing style is different if I'm lucky it might have similar components.

**Comment by evilknivel** [comment]
@mightymos good point in have at least one cheap 433mhz door Sensor laying around and will look to it today an come back to you

**Comment by fastriker** [comment]
@mightymos Good idea and thank you for your efforts! 

[These round ones](https://aliexpress.com/item/486746257.html) seems to be pretty cheap. But they are running on a CR2023 and therefore might be not the best choice though.

[These ones](https://aliexpress.com/item/4001022483259.html) are also not to expensive, but have the same problem.

[These ones](https://aliexpress.com/item/399879790.html) have very uncommon batteries.

~~[These ones](https://www.aliexpress.com/item/4001031267158.html) are running on 2 AAA and are super cheap, but not that common.~~

I can also order some and take a look inside.

**Comment by evilknivel** [comment]
For the Last one i can tell you that they dont even have a rf Module. They just alarm wenn you Open a window.

**Comment by fastriker** [comment]
@evilknivel Thank you! They advertise it with "Wireless Frequency: 433 MHZ Transmission Distance: About 120m without barrier" :/

**Comment by frollard** [comment]
> @fastriker Sorry mate, VPN won't help: If I change the shipping country from Belgium to Germany, I get a "Page Not Found", so it looks like the seller won't deliver to Germany for some reason.

May be related: I've seen discussions on the aliexpress subreddit where several EU countries with plastic packaging bans (austria for example) will only allow import if there is a local company that will handle the packaging waste, then freight forward the plastic-stripped item to the end user. If the country doesn't have a freight forwarder, all the items disappear from ali.

**Comment by Jason2866** [comment]
Don't think the plastic bags are the reason. I do get stuff in plastic bags from Ali here in Germany. My guess it is the VAT which the seller has to handle now.

**Comment by evilknivel** [comment]
@fastriker they are so lound with this piezzo speaket you can hear them from 120m distace that i can confirm. 😂

**Comment by mightymos** [comment]
@fastriker 
Thank you for the list, I guess we will find out...
My concern is that many list the 1527 format.
This could just be protocol choice as discussed below OR maybe they are using a particular chip EV1527.
In that case I guess there might be no separate microcontroller to reflash :
http://www.sc-tech.cn/en/EV1527.pdf

**Comment by fastriker** [comment]
@mightymos Thank you! The fact that they are running with another voltage level 3V/12V already suggest, that the hardware is different. Of course it could have the same chip in the end, but it is not just another housing - unfortunately.

I saw [a German article](https://heise.de/-7454224) about the regulations @frollard  mentioned. I do not know it, but eventually it is the reason for the geoblocking.

**Comment by Jason2866** [comment]
@fastriker The package litter problem is only hitting Austria. The other Sellers not delivering to some Country's is caused by VAT the seller has to do for the target country.
Some Sellers just want not to do, so the can't offer for this country's.

**Comment by mightymos** [comment]
@frollard @zindy @fastriker @evilknivel @Jason2866 
Unfortunately bad news, I ordered a variety of sensors and none use the STC MCUs as best I can tell.
Many have soic (8 pin) without markings but measured voltage supply pins do not match expected STC pinout.

One promising board actually had pads for programming, but no datasheet was found (fmd j2n1gkh microcontroller [freemont micro devices]).
Additionally it appeared to be an I2C, IIC, or SPI interface (maybe it was three pins?) so perhaps more cumbersome and would require external programming hardware.

However, I recommend looking at the current price list in the readme if interested.

![PXL_20230210_220618247](https://user-images.githubusercontent.com/26175234/218212266-ca281dc1-09df-4de5-a0db-9d472346f019.jpg)

**Comment by zindy** [comment]
@mightymos

Wow, thank you for your thorough investigation! I see on your project page that compatible widgets can be purchased on amazon.de (although at twice the original price), that will be good news for @fastriker and @evilknivel

Take care mate!

**Comment by evilknivel** [comment]
very nice that we now have an other way to get the devices. Thank you

**Comment by fastriker** [comment]
Thank you very much @mightymos for your invest in time and money for the research!
I will make an order on amazon for testing and hope for cheaper options in the future to equip the whole flat :)

**Comment by mightymos** [comment]
Now listing compatible sensors in readme
