### ISSUE TITLE
different variant v1.9 2023 - maybe compatible?

### ISSUE THREAD

**Issue by fightforlife** [mightymos/door-reed-rf#14]
Hi there, 
I bought the following magnetic door/window sensors from Alieexpress.
https://de.aliexpress.com/item/1005006306150712.html
The have a different (maybe newer) board layout and sensor.
But I am hopful that they are still using STC15W101/104 8051 + SYN115. The pinning matches and I am pretty sure there are no big developments going on in this sector.

But sadly I was not able to connect via stcgal and an CH341A to the chip.
I can see some repeating data on the pins with a serial monitor when disconnecting the magnet which seems to be the data for the syn115.

Sadly these devices only send a message when the magnet is removed, not when placed back.
Any idea how to identify if this chip is a stc15w-Variant?

I also found someone else trying to modiy these without success a few years back (v1.2):
https://www.weidlinger.at/fenster-tuer-einbrecher-alarm-sensor-wireless-433mhz-china-fuer-projekt-openhab2/

<img width="615" alt="image" src="https://github.com/user-attachments/assets/a07341ce-9d2f-460b-a512-01715c303aaf">
<img width="268" alt="image" src="https://github.com/user-attachments/assets/71621170-5010-4a3d-b3ec-56538a9fbf30">
<img width="169" alt="image" src="https://github.com/user-attachments/assets/05cab54d-9494-4a29-8d5f-18a112b6a380">
<img width="163" alt="image" src="https://github.com/user-attachments/assets/477690e1-243d-4351-8cf4-0f8c27f3abc3">

**Comment by mightymos** [comment]
I did try to look at alternatives previously but did not have much luck:
https://github.com/mightymos/ReedTripRadio/issues/1

As I recall some chips are another microcontroller or use non-reprogrammable parts like this:
http://www.sc-tech.cn/en/EV1527.pdf

It is difficult for me to tell the pinout from the pictures.
Can you tell me what you think the pinout starting from the indented circle (pin1)?
Do you have a multimeter or can see visually at least where power and ground go on 8-pin chip and three pin connector?

**Comment by fightforlife** [comment]
What I found so far:

Controller (unmarked)
Pin 1 is connected to BAT+ (and the 3-Pin-Header H2)
Pin 2 is not connected
Pin 3 is connected to via the magnet-switch H1 to BAT+ (and the 3-Pin-Header H2)
Pin 4 is connected to via the physical-switch to BAT- (and the 3-Pin-Header  H2)
Pin 5 is connected to Pin 4 of the transmitter
Pin 6 is connected to unpopulated R3 to BAT-/GND
Pin 7 is is connected via R4 and via LED to BAT+
Pin 8 is connected to BAT-/GND and the 3-Pin-Header

This could be an attiny202/402. (the unpoulated header H2 seems to be for an additional magnet-switch)
I tried avrdude with an CH341A and serialupdi on 6 for a few minutes but did not get a response. (most likely bacue I did not spend much time on the correct resistor values.)
Interestingly the LED is flashing for the first 2 seconds after power on. Immediately after is sends the standard code with solid led and then turns off. Pressing the buttons again sends the standard code with solid led.
Maybe the flashing after power on is indicating something.


Radio (Markings F44558, 347)
Pin 1 is connected to GND and the Antenna
Pin 2 is connected to GND
Pin 3 is connected to BAT+
Pin 4 is connected to Pin5 of the Controller
Pin 5 is connected via C12 to Crystal and GND
Pin 6 is connected via 13.560 Crystal to GND
This looks like a SYN113/115, But PIN 4 and 6 seem reversed. strange.

**Comment by mightymos** [comment]
![Screenshot 2024-07-27 170346](https://github.com/user-attachments/assets/50d1fb29-1ef2-4b8d-9078-abdfae3692f3)

Ok this is the pinout for the STC15, so it does not seem to match what you've observed on the other board.
It's difficult to know what the part could be without extensive trial and error guessing.

I guess the links in the readme are still working to show STC15 based sensors.
However, the Zigbee sensors are nearly the same price now and maybe those are easier to use with the Home Assistant ZBT-1 or similar. I don't know the state of open source for those though.
