### ISSUE TITLE
Type of micro - STC15W101

### ISSUE THREAD

**Issue by Zodiac-69** [mightymos/door-reed-rf#2]
Thank you for your work.
I bought these on Banggood - [GS-WDS07 Wireless Door Magnetic Strip 433MHz](https://www.banggood.com/GS-WDS07-Wireless-Door-Magnetic-Strip-433MHz-for-Security-Alarm-Home-System-p-1174915.html?cur_warehouse=CN)
So the units i have is 15W101.
Voltage: 5.5 - 2.5
Flash: 1kB
SRAM: 128B
EEPROM: 4k
WDT: Y

Do you have a pre-compiled file one can just upload?

**Comment by mightymos** [comment]
I can certainly generate a .ihx or .hex file but I'll need to see if the system frequency trimming is going to be a problem.
I'll comment again once I upload the hex.

**Comment by Jason2866** [comment]
Just did a PR to build the Firmware with GH Actions and pushing the builded firmware as release.
Edit: PR is merged. Prebuilt is now in release section.

**Comment by mightymos** [comment]
@Zodiac-69 
When you run stcgal-patched can you list your output here?
Specifically what target frequency does it report?

**Comment by mightymos** [comment]
@Zodiac-69 
This release should work on your processor now.
The delay macros use 24MHz as specified by the makefile.
Also running "make upload" will set the trim option to set the processor system clock to the same frequency.

**Comment by Zodiac-69** [comment]
Hi mightymos

This is my unit settings with Stock firmware:
Checking target MCU ... 
  MCU type: STC15W101
  F/W version: 7.2.5T

Current H/W Option:
  . Current system clock source is internal IRC oscillator
  . Current frequency: 11.051MHz
  . Wakeup Timer frequency: 35.700KHz
  . Do not detect the level of P3.2 and P3.3 next download
  . Power-on reset, use the extra power-on delay
  . RESET pin behaves as IO pin
  . Reset while detect a Low-Voltage
  . Thresh voltage level of the built-in LVD : 2.66 V
  . Inhibit EEPROM operation under Low-Voltage  . CPU-Core supply level : 2.73 V
  . Hardware do not enable Watch-Dog-Timer
  . Watch-Dog-Timer pre-scalar : 256
  . Watch-Dog-Timer stop count in idle mode
  . Program can modify the Watch-Dog-Timer scalar
  . Do not erase user EEPROM area at next download
  . Do not control 485 at next download
  . Do not check user password next download
  . TXD is independent IO
  . TXD pin as quasi-bidirectional mode after reset
  . P3.3 output HIGH level after reset
  . Reference voltage: 1255 mV (Range: 1150~1320mV)
  . Testing time: 2019-10-21

  MCU type: STC15W101
  F/W version: 7.2.5T


  Complete !(2023-01-28 10:02:38)

**Comment by mightymos** [comment]
Thanks for the output @Zodiac-69 
You should be able to flash one of the recently released ihx (hex) files.
I also included explicit command line instructions for flashing premade hex in recent readme.

I know other users are testing this firmware with their various receivers.
If your sensors are working with stock settings you may want to wait to flash until others have confirmed things are working well (and with specific receivers). However others have successfully received codes.

**Comment by mightymos** [comment]
Premade HEX files are now available and flashing instructions are more clearly explained in readme.
