### ISSUE TITLE
2nd Flash impossible

### ISSUE THREAD

**Issue by Minims** [mightymos/door-reed-rf#7]
Hello, 

I have flash the version 0.3.3 with success. I am trying to flash 0.3.5 ( or any version now) and I am blocked on 
```
Waiting for MCU, please cycle power:
```
I remove GND or VCC, but nothing appears, there is no data on serial port 1200b. 
Any other way to enter flash mode ? 
Pin are connected correctly and device stil working great. It works on a stock one.

**Comment by mightymos** [comment]
I think v.0.3.3 had tamper startup check enabled, so if you hold down the tamper button on power up it should keep resetting and looking for bootloading.

I normally do it this way:
Disconnect USB module from computer.
Connect UART ground, tx, and rx to sensor board.

Connect USB module to computer.
Execute flashing command on computer.
Hold tamper switch and keep holding it.
Apply power to sensor board.

Did that work?

**Comment by Minims** [comment]
It’s working! Thanks
