### ISSUE TITLE
(Resolved) How do i - compile without re-transmitting of reed and tamper status

### ISSUE THREAD

**Issue by Zodiac-69** [mightymos/door-reed-rf#8]
I would like to use the unit as a Garage door status monitor.
Reed: - Contact closed (Door Closed) - Contact open (Door not Closed)
Trip: - Contact closed (Door Open) - Contact open (Door not Open)
But i don't require the re-transmit if the Reed or the Trip is open.
Where do i disable the re-transmit of the Reed and Trip status?

I have commented out line 139 and 130
// about ten minutes
//#define TAMPER_SLOT 38
//#define REED_SLOT   38
and from line 552 to 591 thinking that it will then not "Re-Transmit" the status

What else do i need to set / disable or am i doing it completely wrong?

**Comment by mightymos** [comment]
Sure, you need to change the line above "TAMPERS_ENABLED" true from #if 1 to #if 0

**Comment by Zodiac-69** [comment]
Thank you.
